#!/usr/bin/env bash

set -euo pipefail

SCRIPTDIR=$(dirname -- "$(readlink -f -- "$0")")

TASKMASTER_LIB="$SCRIPTDIR/.lib"
TASKMASTER_CACHE="$HOME/.cache/taskmaster"

TASKMASTER_HISTFILE="$TASKMASTER_CACHE/history"
TASKMASTER_PROMPT="taskmaster> "

# shellcheck source=".lib/config.sh"
source "$TASKMASTER_LIB/config.sh"

# shellcheck source=".lib/task.sh"
source "$TASKMASTER_LIB/taskmaster.sh"

# TODO: Implement multiple instances
# TODO: Implement retry
# TODO: Implement setuid setgid
# TODO: Set umask
# TODO: Implement daemon mode with ipc
# TODO: Start enabled tasks at init

taskmaster.init

mkdir -p "$TASKMASTER_CACHE"

[ -f "$TASKMASTER_HISTFILE" ] || printf '' > "$TASKMASTER_HISTFILE"

history -r "$TASKMASTER_HISTFILE"

set -o vi

while read -e -p "$TASKMASTER_PROMPT" -r -a token
do
	set -- "${token[@]}" 

	[ "$#" -ge 1 ] || continue

	cmd="$1"; shift

	case "$cmd" in
		enable)		taskmaster.enable "$@"	|| :;;
		disable)	taskmaster.disable "$@"	|| :;;

		start)		taskmaster.start "$@"	|| :;;
		stop)		taskmaster.stop "$@"	|| :;;
		restart)	taskmaster.restart "$@"	|| :;;
		reload)		taskmaster.reload "$@"	|| :;;

		status)		taskmaster.status "$@"	|| :;;

		exit)		exit 0;;

		*)			error "Unknown command '$cmd'!" || :;;
	esac

	history -s "${token[*]}"
done

history -w "$TASKMASTER_HISTFILE"
