#!/usr/bin/env bash

set -euo pipefail

SCRIPTDIR=$(dirname -- "$(readlink -f -- "$0")")

TASKMASTER_LIB="$SCRIPTDIR/.lib"

# shellcheck source=".lib/config.sh"
source "$TASKMASTER_LIB/config.sh"

# shellcheck source=".lib/task.sh"
source "$TASKMASTER_LIB/taskmaster.sh"

# TODO: Implement multiple instances
# TODO: Implement retry
# TODO: Implement setuid setgid
# TODO: Set umask
# TODO: Implement daemon mode with ipc
# TODO: Start enabled tasks at init

taskmaster.init

while read -p "taskmaster> " -ra token
do
	set -- "${token[@]}" 

	[ "$#" -ge 1 ] || continue

	cmd="$1"; shift

	case "$cmd" in
		enable)		taskmaster.enable "$@" || :;;
		disable)	taskmaster.disable "$@" || :;;
		start)		taskmaster.start "$@" || :;;
		stop)		taskmaster.stop "$@" || :;;
		restart)	taskmaster.restart "$@" || :;;
		status)		taskmaster.status "$@" || :;;
		exit)		exit 0;;
		*)			echo "Unknown command '$cmd'!" >&2;;
	esac
done

echo
