# shellcheck shell=bash
# shellcheck disable=SC2034

TASKMASTER_HOME="${TASKMASTER_HOME:-.}"
TASKMASTER_LIB="${TASKMASTER_LIB:-$TASKMASTER_HOME/.lib}"

AVAILABLE_DIR="${AVAILABLE_DIR:-available}"
ENABLED_DIR="${ENABLED_DIR:-enabled}"
RUNNING_DIR="${RUNNING_DIR:-running}"
STOPPING_DIR="${STOPPING_DIR:-stopping}"

TASK_SUFFIX="${TASK_SUFFIX:-.task}"
RUN_SUFFIX="${RUN_SUFFIX:-.pid}"

DEFAULT_PROCESS_COUNT="${DEFAULT_PROCESS_COUNT:-1}"
DEFAULT_RESTART="${DEFAULT_RESTART:-always}"
DEFAULT_SUCCESS_STATUS="${DEFAULT_SUCCESS_STATUS:-0}"
DEFAULT_MIN_RUNTIME="${DEFAULT_MIN_RUNTIME:-0s}"
DEFAULT_RETRY="${DEFAULT_RETRY:-0}"
DEFAULT_STOP_SIGNAL="${DEFAULT_STOP_SIGNAL:-INT}"
DEFAULT_STOP_TIMEOUT="${DEFAULT_STOP_TIMEOUT:-30s}"
DEFAULT_STDOUT="${DEFAULT_STDOUT:--}"
DEFAULT_STDERR="${DEFAULT_STDERR:--}"
DEFAULT_UMASK="${DEFAULT_UMASK:-022}"
DEFAULT_UID="${DEFAULT_UID:-}"
DEFAULT_GID="${DEFAULT_GID:-}"
